apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-github-tekton-artifactory-100625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-github-tekton-artifactory-100625 
  name: dotnet-github-tekton-artifactory-100625
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet-github-tekton-artifactory-100625
    weight: 100 
